version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fleetdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: fleetdb  # Ensure this is set correctly
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3308"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
