server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fleetdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false?allowPublicKeyRetrieval=true
    username: root
    password: root

  sql:
    init:
      mode: always