name: Deploy to Railway

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Authenticate Railway
        run: railway login --token ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Deploy to Railway
        run: railway up
